name: CI/CD para Django

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Actualizar pip y crear entorno virtual
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate

      - name: Instalar dependencias
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Aplicar migraciones
        run: |
          source venv/bin/activate
          python manage.py migrate

      - name: Ejecutar pruebas automatizadas
        run: |
          source venv/bin/activate
          pytest --maxfail=5 --disable-warnings -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Crear entorno virtual e instalar dependencias
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Desplegar aplicación (Ajusta según tu entorno)
        run: |
          echo "Aquí iría tu comando de despliegue"
