name: CI/CD para Django

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Aplicar migraciones
        run: |
          source venv/bin/activate
          python manage.py migrate

      - name: Ejecutar pruebas automatizadas
        run: |
          source venv/bin/activate
          pytest --maxfail=5 --disable-warnings -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Iniciar sesión en Docker Hub
        run: echo "${{ secrets.DOCKERPASSWORD }}" | docker login -u "${{ secrets.DOCKERUSERNAME }}" --password-stdin

      - name: Construir imagen Docker
        run: docker build -t ${{ secrets.DOCKERUSERNAME }}/web_user_django:latest .

      - name: Subir imagen a Docker Hub
        run: docker push ${{ secrets.DOCKERUSERNAME }}/web_user_django:latest

      - name: Desplegar en servidor remoto (Opcional)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no $USER@$SERVER_IP << 'EOF'
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/web_user_django:latest
          docker stop web_user_django || true
          docker rm web_user_django || true
          docker run -d -p 8000:8000 --name web_user_django ${{ secrets.DOCKER_HUB_USERNAME }}/web_user_django:latest
          EOF
